on:
    workflow_run:
          workflows: ['Integration Tests']
          types: [completed]
    push:
      branches:
        - main
        - master


name: "Build & Release"

jobs:
    build: 
        name: Build & Release
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
          - uses: subosito/flutter-action@v2
            with:
                channel: stable
                flutter-version: '3.19.5'
          - name: Dependencies install
            run: flutter pub get
          - name: Integration Test
            run: flutter test -d windows integration_test\app_test.dart 
          - name: Build For Windows
            run: flutter build windows --release --build-name 1.1.${{ github.run_number }} --build-number ${{ github.run_number }}
          - name: Archive Release
            uses: thedoctor0/zip-release@master
            with:
                type: 'zip'   
                filename: Sangeet-v1.1.${{ github.run_number }}_windows_x64.zip
                directory: build/windows/x64/runner/Release
          - name: Push to Releases
            uses: ncipollo/release-action@v1
            with:
                artifacts: "build/windows/x64/runner/Release/Sangeet-v1.1.${{ github.run_number }}_windows_x64.zip"
                tag: v1.1.${{ github.run_number }}
                token: ${{ secrets.GITHUB_TOKEN }}