on:
    pull_request:
        branches:
          - main
          - master
    push:
      branches:
        - main
        - master


name: "Integration Tests"

jobs:
    run_tests: 
        name: Run Integration Tests
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
          - uses: subosito/flutter-action@v2
            with:
                channel: stable
                flutter-version: '3.19.5'
          - name: Test Connectivity
            run: |
              ping jiosaavn.com
          - name: Dependencies install
            run: flutter pub get
          - name: Test For Windows
            run: flutter test -d windows integration_test\app_test.dart 
          - name: Build For Windows
            run: flutter build windows
